### ISSUE TITLE
Early config availability

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2589]
The new config system needs to be available before a `QApplication` is created.

This will allow:

- [x] Passing custom switches to Chromium (#2235, #2377, probably also a config option for custom switches)
- [ ] Adding an option for the `QT_XCB_FORCE_SOFTWARE_OPENGL` environment var (#2368)
- [ ] Fixing the wayland decoration option (#2267)
- [ ] ~~Adding an option to toggle accessibility for performance reasons (see [this Qt change](https://codereview.qt-project.org/#/c/193002/1//ALL,unified))~~
- [x] Adding an option to switch the backend

**Comment by The-Compiler** [comment]
Quick update: There's a `backend` and a `qt_args` option now, hopefully making wrapper scripts a thing of the past!

**Comment by The-Compiler** [comment]
Only #2368 and #2267 are left, so I'm closing this one.
