### ISSUE TITLE
qute://settings improvements

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#275]
UI:
- [ ] Maybe show rendered HTML for config sections?
- [ ] Maybe show value descriptions. Check [_get_setting_quickref](https://github.com/The-Compiler/qutebrowser/blob/f4876c7f4fdba1c0e3461a5cbfa3924d9a209ff5/scripts/src2asciidoc.py#L127-L143) and [generate_settings](https://github.com/The-Compiler/qutebrowser/blob/f4876c7f4fdba1c0e3461a5cbfa3924d9a209ff5/scripts/src2asciidoc.py#L280-L313) in `scripts/src2asciidoc.py` for some inspiration.
- [ ] Matching config types to html input types
  - [ ] colors = html colorpicker
  - [ ] options with valid_values = select/multi-select
  - [ ] plain text fallbacks where appropriate
  - [ ] multi-line text edits for long options (i.e. host-block-lists)
- [ ] Javascript option verification
  - [ ] switch from submitting changes onblur to onchange if an option passes basic
    verification, etc.
- [ ] restyle to match `qute:settings` and `qute:bookmarks`
- [ ] Support per-domain settings
- [ ] Add error handling for requests
- [ ] Use POST instead of GET for `qute://settings/set` (also see #4060, though forms allow POST)
- [ ] Since #4060, if `qute://settings` is open in multiple tabs, it only works in the last opened one due to the CSRF token
- [ ] Since #4060, opening `qute://settings/asfiasf` shows a setting page, but it doesn't work.

cc @iggy

**Comment by DrTobe** [comment]
The qute://settings page should also say how to store the changes made there, I think. I found out how to do it by chance.

**Comment by The-Compiler** [comment]
FWIW, the changes are saved immediately, as soon as the edited field loses focus.
