### ISSUE TITLE
New config TODO after new completion is merged

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2779]
In the `new-config` branch, some stuff is disabled until #2295 is merged. That should be cleaned up and re-enabled - and there are some other changes, too.

- [x] Aliases completion for commands
- [x] Setting tests in `completion.feature`
- [x] Most stuff in `tests/unit/completion`
- [x] Config section/option/value completions 
- [x] `:bind` completion
- [x] Help topic completion
- [x] vulture whitelist for config completions
- [x] flake8 ignore for `test_models.py`
- [x] pylint ignores in `miscmodels.py`, `configmodel.py`, `test_models.py`
- [x] Old config references in completion tests (like `quick-complete`)
- [x] keyconf init got moved to `app.py` / `keyconf.py` (because of a circular import, IIRC?) - remove that part again.
- [x] Make sure to remove `web-history-max-items`
- [x] Move `Scenario: Open qute://version` from `misc.feature` to `quteurls.feature`
- [x] Move `test_history.py` unittests out of `webkit/`
- [x] Make sure the `web-history-max-items` setting has `int64` as `maxval`
- [ ] Look at using `CommandParser` for `miscmodels.bind`
- [x] Review `git diff 2f264905369193d1416925415abf2fc1a4c0e289..master -- qutebrowser/config/configdata.py`

cc @rcorre

**Comment by rcorre** [comment]
I've checked off some of the above based on work in #2914 (not yet merged to master)

**Comment by The-Compiler** [comment]
Split off the one remaining part to #2952 now that #2914 is in.
