### ISSUE TITLE
New QtWebEngine features in Qt 5.11

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3010]
It's going to take a while (Qt 5.11 is planned for May 2018), but recording interesting Qt 5.11 changes here:

# New in Qt 5.11

- [x] [More `chrome://` URLs](https://codereview.qt-project.org/#/c/205250/)
- [x] [Quota management API](https://codereview.qt-project.org/#/c/174136/)
- [x] [Support for registering protocol handlers](https://codereview.qt-project.org/#/c/216756/)
- [x] [Unknown scheme handling](https://codereview.qt-project.org/#/c/199125/) (`UnknownUrlSchemePolicy`, #2833)
- [x] [Autoplay option](https://codereview.qt-project.org/#/c/209240/) (`PlaybackRequiresUserGesture`)
 (#1643)
- [x] [Better developer tools](https://codereview.qt-project.org/#/c/205251/)
- [x] [WebRTC option](https://codereview.qt-project.org/#/c/204221/) (`WebRTCPublicInterfacesOnly`) (#2163)
- [x] [Cookie blocking API](https://codereview.qt-project.org/#/c/204302/)
- [x] [JavaScriptCanPaste attribute](https://codereview.qt-project.org/#/c/209551/) (not planning to expose this due to security considerations)
- [x] Hopefully working Wayland support (#2932)

# Didn't make it (5.12 maybe?)

- [Notification API](https://codereview.qt-project.org/#/c/205716/)
- [Do Not Track setting](https://codereview.qt-project.org/#/c/204224/)

# Not submitted yet (5.12 maybe?)

- [Getting QWebEnginePage from download](http://paste.the-compiler.org/view/4bbdd4cb) (might also help to close blank pages after a download is started)

**Comment by nemanjan00** [comment]
Any idea on when can we expect devtools?

**Comment by The-Compiler** [comment]
@nemanjan00 devtools are already there since August 2016, with the caveat that you need to run qutebrowser with `--enable-webengine-inspector` and it listens on a local port (which is a [security problem](http://bouk.co/blog/hacking-developers/).

This is about better devtools integration maybe landing in Qt 5.11, which is planned for May 2018. Note the change isn't in yet, though.

**Comment by nemanjan00** [comment]
So, I do need external inspector or?

**Comment by The-Compiler** [comment]
No, you start qutebrowser with `--enable-webegine-inspector` and run `wi`/`:inspect`.

**Comment by The-Compiler** [comment]
Trying the `QWebEngineDownload::page` change, I've run into two problems:

- I've had to add `QWebEnginePage *page;` to `src/webenginewidgets/api/qwebenginedownloaditem_p.h`
- I'm now getting assertion errors when running qutebrowser's testsuite:

```
ASSERT: "!m_ongoingDownloads.contains(info.id)" in file api/qwebengineprofile.cpp, line 192
```

```
#7 0x7fe29bc0185d QMessageLogger::fatal()
#8 0x7fe29bbfa360 qt_assert()
#9 0x7fe28f20b2fe QWebEngineProfilePrivate::downloadRequested()
#10 0x7fe27f2b2bb2 QtWebEngineCore::DownloadManagerDelegateQt::DetermineDownloadTarget()
#11 0x7fe280a2dc85 content::DownloadManagerImpl::DetermineDownloadTarget()
#12 0x7fe280a075a4 content::DownloadItemImpl::DetermineDownloadTarget()
#13 0x7fe280a072c9 content::DownloadItemImpl::OnDownloadFileInitialized()
#14 0x7fe280a26101 _ZN4base8internal13FunctorTraitsIMN7content16DownloadItemImplEFvNS2_23DownloadInterruptReasonEEvE6InvokeIRKNS_7WeakPtrIS3_EEJS4_EEEvS6_OT_DpOT0_
#15 0x7fe280a2270d _ZN4base8internal12InvokeHelperILb1EvE8MakeItSoIRKMN7content16DownloadItemImplEFvNS4_23DownloadInterruptReasonEERKNS_7WeakPtrIS5_EEJS6_EEEvOT_OT0_DpOT1_
#16 0x7fe280a1c49c _ZN4base8internal7InvokerINS0_9BindStateIMN7content16DownloadItemImplEFvNS3_23DownloadInterruptReasonEEJNS_7WeakPtrIS4_EEEEEFvS5_EE7RunImplIRKS7_RKSt5tupleIJS9_EEJLm0EEEEvOT_OT0_NS_13IndexSequenceIJXspT1_EEEEOS5_
#17 0x7fe280a1702a _ZN4base8internal7InvokerINS0_9BindStateIMN7content16DownloadItemImplEFvNS3_23DownloadInterruptReasonEEJNS_7WeakPtrIS4_EEEEEFvS5_EE3RunEPNS0_13BindStateBaseEOS5_
#18 0x7fe2809fbeb9 _ZNKR4base8CallbackIFvN7content23DownloadInterruptReasonEELNS_8internal8CopyModeE1ELNS4_10RepeatModeE1EE3RunES2_
#19 0x7fe2809fac18 _ZN4base8internal13FunctorTraitsINS_8CallbackIFvN7content23DownloadInterruptReasonEELNS0_8CopyModeE1ELNS0_10RepeatModeE1EEEvE6InvokeIRKS8_JRKS4_EEEvOT_DpOT0_
#20 0x7fe2809f93d7 _ZN4base8internal12InvokeHelperILb0EvE8MakeItSoIRKNS_8CallbackIFvN7content23DownloadInterruptReasonEELNS0_8CopyModeE1ELNS0_10RepeatModeE1EEEJRKS6_EEEvOT_DpOT0_
#21 0x7fe2809f605b _ZN4base8internal7InvokerINS0_9BindStateINS_8CallbackIFvN7content23DownloadInterruptReasonEELNS0_8CopyModeE1ELNS0_10RepeatModeE1EEEJS5_EEEFvvEE7RunImplIRKS9_RKSt5tupleIJS5_EEJLm0EEEEvOT_OT0_NS_13IndexSequenceIJXspT1_EEEE
#22 0x7fe2809f42e6 _ZN4base8internal7InvokerINS0_9BindStateINS_8CallbackIFvN7content23DownloadInterruptReasonEELNS0_8CopyModeE1ELNS0_10RepeatModeE1EEEJS5_EEEFvvEE3RunEPNS0_13BindStateBaseE
#23 0x7fe27f883aab _ZNO4base8CallbackIFvvELNS_8internal8CopyModeE0ELNS2_10RepeatModeE0EE3RunEv
#24 0x7fe282f87538 base::debug::TaskAnnotator::RunTask()
#25 0x7fe282d5ffc2 base::MessageLoop::RunTask()
#26 0x7fe282d60159 base::MessageLoop::DeferOrRunPendingTask()
#27 0x7fe282d605fe base::MessageLoop::DoWork()
#28 0x7fe27f2994bd QtWebEngineCore::(anonymous namespace)::MessagePumpForUIQt::customEvent()
#29 0x7fe29be35466 QObject::event()
```

**Comment by The-Compiler** [comment]
Feature freeze for Qt 5.11 is now in effect. Unfortunately, notifications didn't make it... But there's still some awesome stuff going to come with 5.11!

**Comment by tloring-denovix** [comment]
D'oh, did not see that reference to 5.12 up top...thanks!

**Comment by The-Compiler** [comment]
FYI: Initial support for the Qt 5.11 developer tools is now implemented (and will work once PyQt 5.11 is out). From a quick test, it seems to work fine and without needing `--enable-webengine-inspector`.

**Comment by The-Compiler** [comment]
And the rest of the Qt 5.11 features is done as well. Cookie filtering is not in master yet (5fcdf21e1d4e1c9961f8eaacb8dae0f2d9ecd553) because [of issues with PyQt](https://www.riverbankcomputing.com/pipermail/pyqt/2018-June/040394.html) ([which should be fixed tomorrow](https://www.riverbankcomputing.com/pipermail/pyqt/2018-June/040395.html)).

**Comment by The-Compiler** [comment]
All done now! :tada:
