### ISSUE TITLE
Site-specific quirks overview

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4810]
We should probably assemble a list of site-specific quirks (and ship with them by default). Here's what I'm aware of so far:

- [x] WhatsApp needs some UA/JS workarounds (maybe not anymore?): #4445
- [x] Slack needs a custom UA: #4669 
- [ ] ~~Google Drive needs a non-Windows UA: https://github.com/qutebrowser/qutebrowser/issues/4445#issuecomment-487501513~~
- [x] Google Docs needs an UA without "Chrome/": #4805, [QTBUG-69652](https://bugreports.qt.io/browse/QTBUG-69652)
- [ ] HBO Go seems to want a Chromium UA: https://www.reddit.com/r/qutebrowser/comments/cbama6/how_to_watch_hbo_go_drm/eui6k0w
- [ ] ~~WebKitGTK reports needing one for GitHub on FreeBSD: https://webkitgtk.org/2019/07/23/webkitgtk2.25.3-released.html (but that might not be the case for QtWebEngine)~~
- [ ] ~~More WebKit quirks: https://github.com/WebKit/webkit/blob/master/Source/WebCore/platform/UserAgentQuirks.cpp~~
- [x] Google, apparently... https://www.reddit.com/r/qutebrowser/comments/cyb1wi/cant_sign_into_google/
- [ ] More Google-specific stuff from WebKitGTK: https://bugs.webkit.org/show_bug.cgi?id=142074
- [ ] ~~Digitec/Galaxus~~ (seems to be fixed nowadays?)

The web [sure is a fun place](https://webaim.org/blog/user-agent-string-history/)...

**Comment by karlh626** [comment]
**Dell Support pages**
On many Dell Support pages I was getting Access Denied error messages with qutebrowser until I changed the user agent with the following command:

`:set content.headers.user_agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'`

**Comment by The-Compiler** [comment]
@karlh626 Do you have an example link? https://www.dell.com/support/ seems to work fine so far for me.

**Comment by The-Compiler** [comment]
@karlh626 Ah, I could reproduce with Qt 5.7. I'll push a fix together with some other pages/fixes.

@prosoitos Since you gave a :+1: for my Google Drive on Windows comment at https://github.com/qutebrowser/qutebrowser/issues/4445#issuecomment-487501513 I assume you were affected by it? Is this something you can still reproduce nowadays? It seems to work fine for me now.

**Comment by The-Compiler** [comment]
I now pushed a fix for known-broken sites (WhatsApp, Google login, etc.) to the `user-agent` branch. If you're affected by one of those, could you please try that branch without any custom user agent set? Thanks!

**Comment by prosoitos** [comment]
> Since you gave a  for my Google Drive on Windows comment at #4445 (comment) I assume you were affected by it? Is this something you can still reproduce nowadays? It seems to work fine for me now.

Works fine for me too. Thanks!

Until I read this, I had `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.128 Safari/537.36` for my `content.headers.user_agent` (and no issue with google drive).

Removing that setting and going to the default doesn't affect google drive.

**Comment by The-Compiler** [comment]
I just wrote a more detailed explanation for what's going on with the Google Accounts issue: #5182
