### ISSUE TITLE
Settings/bindings changes for v2.0.0

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6022]
This is a follow-up to #5999 for everything I think is clear enough:

- [x] Set `tabs.background` to `true`
- [ ] `d` is going to stay for now, as rebinding it to `dd` was rather controversial - though the idea about delaying tab closes might be worth some exploration. - see #6064
- [ ] Setting `tabs.last_close` to `close` was too controversial - it was proposed to set it to `blank` instead, which might be the way forward.
- [ ] Rename userscripts to qutescripts - see #6063
- [x] Set `hints.leave_on_load` to `false`
- [x] `J` and `K` clearly are going to stay (phew)
- [ ] `content.cookies.accept` should be set to `no-3rdparty`, if possible without breaking major websites - see #5309
- [x] Rename `:buffer` to `:tab-select`
- [ ] Keep `:set`, but maybe make it an alias to `:config-set` (however, aliases don't have completion...)
- [x] Rename `:open-editor` to `:edit-text`
- [x] Rename `:record-macro` and `:run-macro` to swap the words
- [x] For consistency with other commands, `:toggle-selection`, `:drop-selection` and `:reverse-selection` should have the words swapped.
  * [x] Perhaps rename `:follow-selected` to `:selection-follow` as well.
  * [x] For consistency, it'd make sense to rename `:follow-hint` to `:hint-follow` too.
  * [x] Probably `:enter-mode` and `:leave-mode` as well.
- [x] Set `input.partial_timeout` to 0
- [x] Set `tabs.width` to 15%
- [x] Change bindings for tab moving from `gl` / `gr` to `gK` and `gJ`

**Comment by bodograumann** [comment]
Regarding the third-party cookies:
I have been using uMatrix in the past to block them by default and only enable them where really necessary.
This is something which I’m definitely looking to replicate in qutebrowser.  (E.g. Reddit knows about my google account, ugh)
It will probably still break some major sites though.
For example office.com needs cookies from other microsoft domains, iirc.
Maybe a default whitelist could help here?

**Comment by The-Compiler** [comment]
@bodograumann Yeah, I also suspect it's not as easy as just flipping the switch - see #5309 for details on that one. You can already whitelist individual sites yourself with domain patterns, though.

**Comment by The-Compiler** [comment]
Anything that was uncontroversial as well as easy to change is now in. The rest might not make it into v2.0.0 perhaps - will take another look and split them off into separate issues.

**Comment by The-Compiler** [comment]
To make it a bit more discoverable what's going on (without everyone having to read the changelog), I re-added deprecated aliases for the renamed commands.
